In [5]:
import numpy as np
arr1=np.array([2,3,4])
arr1=arr1*5
print(arr1)
print(type(arr1))


[10 15 20]
<class 'numpy.ndarray'>


In [ ]:
#2d array

arr1=np.array([[1,2,3],
    
            [4,5,6]
            ])

print(arr1.ndim)  #dimention

2


In [22]:
#3d array
arr1=np.array([
            [[1,2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])

print(arr1.ndim)
print (arr1.shape)

print(arr1.dtype)


3
(3, 2, 3)
int32


In [23]:
arr1=np.array([
            [[1,2.2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])

print(arr1.ndim)
print (arr1.shape)

print(arr1.dtype)


3
(3, 2, 3)
float64


In [ ]:
arr1=np.array([2,3,4,'3'])

print(arr1)
print(arr1.dtype) #upcasting


['2' '3' '4' '3']
<U11


#selecting a data type for an array


In [29]:
arr=np.array([1,2,3],dtype=np.int8)
print(arr.dtype)

int8


NumPy Upcasting Example

In [5]:
import numpy as np
arr=np.array([1,2,3,4])
print(f"Original Type:{arr.dtype}")

Upcasted_arr=arr+0.5
print(Upcasted_arr)
print(f"Final Type:{Upcasted_arr.dtype}")


Original Type:int32
[1.5 2.5 3.5 4.5]
Final Type:float64


ndarray creating from existing data

In [ ]:
#list
lst=[10,20,30,40.5]
arr=np.array(lst,dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)

[10 20 30 40]
<class 'numpy.ndarray'>
int32


In [11]:
lst=[10,True,'Hello',10.5]
arr=np.array(lst)

print(arr)
print(type(arr))
print(arr.dtype)


['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32


In [ ]:
#list to array
matrix=[[1,2,3],
        [4,5,6]]

print(type(matrix))

arr=np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

<class 'list'>
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


#tuples


In [19]:
tpl=(10,20,30)

arr=np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30]
<class 'numpy.ndarray'>
int32
(3,)
1


#set

In [2]:
import numpy as np
#set convert in array
set1={1,2,3,4,5,6}
arr=np.array(list(set1))
arr=arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int16
(6,)
1


#Dictionary

In [3]:
dic={'a':10,'b':20,'c':30}
print(type(dic))


keys=dic.keys()
print(keys)
values=dic.values()
print(values)
items=dic.items()
print(items)


<class 'dict'>
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])


ndarray creation from scratch

In [39]:
#np.zeros
arr1=np.array([
            [[1,2.2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])
#arr=np.zeros((2,3),dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr=np.zeros_like(arr1)







[10 20 30 40 50 60]
<class 'numpy.ndarray'>
int32
(6,)
1


In [40]:
#np.ones
arr1=np.array([
            [[1,2.2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])
arr=np.ones((2,3),dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr=np.ones_like(arr1)






[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [41]:
#np.empty
arr1=np.array([
            [[1,2.2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])
arr=np.empty((2,3),dtype=np.int32)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr=np.empty_like(arr1)






[[1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int32
(2, 3)
2


In [42]:
#np.full
arr1=np.array([
            [[1,2.2,3], [4,5,6]],
            
            [[1,2,3], [4,5,6] ],
            
             [[1,2,3], [4,5,6] ]
            ])
arr=np.full((4,3),True)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

arr=np.zeros_like(arr1)






[[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]
<class 'numpy.ndarray'>
bool
(4, 3)
2


In [167]:
arr=np.empty_like(arr1)
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [198]:
arr=np.empty_like(arr1)
print(arr)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


nd array generation with  random value

In [199]:
#np.random.rand(shape)

arr=np.random.rand(2,3)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)



[[0.73084456 0.86267539 0.29391123]
 [0.79355497 0.37717106 0.53858238]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [200]:
arr=np.random.randint(1,10,(10,10))

print(arr)
print(type(arr))
#print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 5 5 9 3 5 4 5 4 5]
 [7 9 8 8 9 3 8 2 1 5]
 [8 1 6 6 5 9 6 1 7 5]
 [7 8 5 7 8 6 7 4 6 4]
 [1 5 6 7 8 8 5 1 8 1]
 [3 3 3 7 2 6 4 3 2 8]
 [4 2 2 3 5 7 5 8 6 7]
 [6 2 8 9 8 2 8 8 4 8]
 [3 1 1 4 7 6 3 4 3 7]
 [8 3 6 4 2 1 9 6 8 3]]
<class 'numpy.ndarray'>
(10, 10)
2
100


In [201]:
#np.random.unifrom(start,end,shape)
arr=np.random.uniform( 50,100,(3,3,4))

print(arr)
print(type(arr))
#print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[67.41970819 77.44357621 75.26679392 96.34217915]
  [64.40068646 91.8378202  79.37774438 74.28891117]
  [83.04176722 57.0712797  53.73805595 78.04407749]]

 [[86.65197925 75.0515414  51.9654239  94.29519769]
  [79.28658688 83.20301069 76.54755358 79.45369374]
  [89.26895007 94.08153088 63.34533042 66.42532724]]

 [[78.65696449 62.02737358 69.56873291 61.08144798]
  [59.65245282 92.10235231 94.02698182 94.13977125]
  [58.78841082 74.98599498 65.40989761 53.2554563 ]]]
<class 'numpy.ndarray'>
(3, 3, 4)
3
36


nd array creation from range

In [202]:
#np.arange(first,end,step) ->similar to range function
arr=np.arange(1,10,2)


print(arr)
print(type(arr))
#print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)


[1 3 5 7 9]
<class 'numpy.ndarray'>
(5,)
1
5


indexing and slicing


In [203]:
#Basic Indexing (1D Arrays)
import numpy as np
arr=np.array([10,20,30,40,50])
#print(arr[0]) 
#print(arr[1]) 

#print(arr[1:4])
#print(arr[:3])
#print(arr[2:])
print(arr[::2])  #jumps 2 steps
print(arr[0:4:2]) #[start:stop:step]  #step=jump 2 spots

print(arr[::-1]) #reverse
print(arr[4:0:-1]) #reverse from index 4 to 1


[10 30 50]
[10 30]
[50 40 30 20 10]
[50 40 30 20]


#2d Slicing

In [229]:
#2d Slicing
import numpy as np
# 2d array
arr2 = np.array([ [1,2,3], # row1
                  [4,5,6] #row2
                ])

row_0=arr2[::,0:1]

print(row_0)


[[1]
 [4]]


Advanced Indexing

In [230]:
import numpy as np
t=np.array([10,20,30,40])
values=t[[0,3,1]]
print(values)


[10 40 20]


Boolean Indexing(Filtering)

In [231]:
Data=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
mask=Data>7
mask2=Data%2==0
print(mask)
print(Data[mask])
print(Data[mask2])



[False False False False False False False  True  True  True  True  True
  True  True  True  True]
[ 8  9 10 11 12 13 14 15 16]
[ 2  4  6  8 10 12 14 16]


Machine Learning (ML), NumPy indexing and slicing

In [232]:
import numpy as np

dataset=np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(dataset[:,:-1])

[[1 2]
 [4 5]
 [7 8]]


In [254]:
print(dataset[:,-1])

[3 6 9]


In [255]:
print(dataset[:-2,-1])

[3]


In [256]:
train_data=dataset[:3,:]
print(train_data)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [257]:
train_data=dataset[3:,:]
print(train_data)


[]


Ndarray Copy Advanced Indexing and  Iteration

NumPy Copy vs View

In [258]:
import numpy as np
original=np.array([1,2,3,4,5])

view_arr=original[0:3]
view_arr[0]=99

print(original)
print(view_arr)


[99  2  3  4  5]
[99  2  3]


copy


In [259]:
copy_arr=original.copy()
copy_arr[1]=100
print(original)
print(copy_arr)

[99  2  3  4  5]
[ 99 100   3   4   5]


Advanced Indexing

1.Integer Array Indexing

In [260]:
arr=np.array([10,20,30,40,50,60])
indices=[0,2,4]
print(arr[indices])

[10 30 50]


2.Boolean Indexing

In [261]:
data=np.array([1,5,8,12,15])
print(data[data>8])

[12 15]


3d array

In [262]:
arr2 = np.array([[10, 20, 30], 
                 [40, 50, 60], 
                 [70, 80, 90]])

In [263]:
#if print 30
print(arr2[0,2])

30


In [264]:
#if print 90
print(arr2[2,2])

90


In [265]:
print(arr2[arr2<100])

[10 20 30 40 50 60 70 80 90]


In [266]:
#print number which are grater than 50
print(arr2[arr2>50])

[60 70 80 90]


Iteration

In [267]:
arr_2d=np.array([[1,2],
                 [3,8],
                 [12,9]
                 ])
#using for loop
for i in arr_2d:
    print(i)

[1 2]
[3 8]
[12  9]


In [268]:
# iteration nditer() function
arr_2d=np.array([[1,2],
                 [3,8],
                 [12,9]
                 ])
for x in np.nditer(arr_2d):
    print(x)

1
2
3
8
12
9


creating diagonal and identity matrix

In [269]:
import numpy as np
diagonal=np.diag([1,2,3])
print(diagonal)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [270]:
#shape of diagonal array
print(diagonal.shape)

(3, 3)


identity matrix

In [271]:
identity_matrix=np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [272]:
identity_matrix=np.eye(4,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [273]:
identity_matrix=np.eye(4,3,1)  # 1 up to upper
print(identity_matrix)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [274]:
identity_matrix=np.eye(4,3,-1) # 1 up to lower
print(identity_matrix)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
