1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [ ]:
import  numpy as np
#1D array
array1=np.array([1,2,3,4])

array1
print(array1.ndim)
print(array1.shape)

#2d array
array2=np.array([[1,2,3,4],
                [2,3,6,7]])

print(array2.ndim)
print(array2.shape)


#3d array
array3=np.array([
      [[1,2,3,4],
                [2,3,6,7],
                [12,3,5,6]
      ]]
      )

print(array3.ndim)
print(array3.shape)


1
3


2 . Create: 

●  an array of zeros of shape (3,3) 

●  an array of ones of shape (2,5)
  
●  an array filled with 7

In [9]:
array1=np.random.rand(2,3)
print(array1)


array2=np.random.rand(2,5)
print(array2)


#an array filled with 7
array3=np.full((2,3),7)
print(array3)

[[0.68828467 0.34776532 0.04008651]
 [0.01583214 0.58551267 0.54871845]]
[[0.35256683 0.79032382 0.662396   0.71498912 0.57814624]
 [0.05011913 0.1847419  0.33072107 0.4534512  0.95521415]]
[[7 7 7]
 [7 7 7]]


3 . Create an array of even numbers between 10 and 50 using arange.

In [11]:
even_arr=np.arange(10,50,2)
print(even_arr)



[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


4 . Create a 4×4 matrix from 0–15. Then , extract: 

●  the first row  

●  the last column 
 
●  a 2×2 subarray from the center 
 
 
 
 
 

In [12]:
matrix=np.arange(16).reshape(4,4)
print(matrix)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [13]:
#the first row
print(matrix[0])

[0 1 2 3]


In [ ]:
#the last column
print(matrix[:,3])

[ 3  7 11 15]


In [17]:
# 2×2 subarray from the center 
print(matrix[1:3,1:3])

[[ 5  6]
 [ 9 10]]
