Module 9

In [97]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5))


In [109]:
arr

array([[85, 91, 11, 34, 49],
       [33, 77, 77, 81, 13],
       [73, 15, 16, 69, 24],
       [42, 15, 87, 84, 62],
       [11, 40, 10, 16, 35],
       [46, 66,  9, 45, 12],
       [22, 37, 47, 50, 84],
       [ 1, 31, 79, 18, 91],
       [45, 74, 53, 78, 58],
       [61, 66, 38,  3, 11]])

In [120]:
arr.shape


(10, 5)

In [177]:
b=arr.reshape(5,10)
b.shape
b.ndim
b

array([[85, 91, 11, 34, 49, 33, 77, 77, 81, 13],
       [73, 15, 16, 69, 24, 42, 15, 87, 84, 62],
       [11, 40, 10, 16, 35, 46, 66,  9, 45, 12],
       [22, 37, 47, 50, 84,  1, 31, 79, 18, 91],
       [45, 74, 53, 78, 58, 61, 66, 38,  3, 11]])

In [178]:
flatten=b.flatten()  #flatten covert 1 dimentation
#print(flatten.ndim)
flatten


array([85, 91, 11, 34, 49, 33, 77, 77, 81, 13, 73, 15, 16, 69, 24, 42, 15,
       87, 84, 62, 11, 40, 10, 16, 35, 46, 66,  9, 45, 12, 22, 37, 47, 50,
       84,  1, 31, 79, 18, 91, 45, 74, 53, 78, 58, 61, 66, 38,  3, 11])

In [221]:
column_wise_flattening=np.ravel(b,order='F')
print(column_wise_flattening)

[18 11 17 11 16 10]


In [222]:
a=np.random.randint(1,10,size=(2,3))
print(a)

[[8 7 1]
 [5 1 7]]


In [223]:
b=np.random.randint(10,20, size=(2,3))
b


array([[13, 19, 17],
       [14, 16, 19]])

Concatenate

In [224]:
a=np.random.randint(1,10,size=(2,3))
b=np.random.randint(10,20, size=(2,3))

con_row=np.concatenate((a,b),axis=0) #Row 
print(con_row)

con_col=np.concatenate((a,b),axis=1) # column
print(con_col)


[[ 9  7  7]
 [ 4  8  1]
 [16 18 18]
 [18 12 10]]
[[ 9  7  7 16 18 18]
 [ 4  8  1 18 12 10]]


In [225]:
#transpose
mat=np.array([
    [10,20,30],
    [30,40,50]
    
])
transpose=mat.T
print(transpose)

[[10 30]
 [20 40]
 [30 50]]


array spilit

In [230]:
a=np.random.randint(1,10,size=(10,))
a

array([2, 2, 4, 4, 9, 9, 4, 6, 3, 8])

array_split all time

In [1]:
import numpy as np
a=np.random.randint(1,10,size=(10,))
print(a)
splitted_array=np.array_split(a,3)
print(splitted_array)

[2 6 9 8 2 6 4 7 2 8]
[array([2, 6, 9, 8]), array([2, 6, 4]), array([7, 2, 8])]


#split->Equal division

In [7]:
import numpy as np
b=np.random.randint(2,12,size=(10,))
splitted_array=np.split(b,2)
print(splitted_array)

[array([10,  3,  2,  7,  5]), array([11,  5,  3,  3,  8])]


ndarray Arithmetic Operators and Mathematical function

In [11]:
import numpy as np
x=np.array([1,2,3,4,5,6,7,8,9])
y=np.array([10,12,23,4,5,67,9,8,9])
add=np.add(x,y)  #using add function
print(add)

add1=x+y  #using + operator
print(add1)

[11 14 26  8 10 73 16 16 18]
[11 14 26  8 10 73 16 16 18]


In [ ]:
#multipication
mul=np.multiply(x,y) #using multiply function
print(mul)

mul1=x*y  #using *operator
print(mul1)


In [13]:
#division
div=np.divide(x,y) #using divide function
print(div)

div1=x/y  #using / operator
print(div1)


[0.1        0.16666667 0.13043478 1.         1.         0.08955224
 0.77777778 1.         1.        ]
[0.1        0.16666667 0.13043478 1.         1.         0.08955224
 0.77777778 1.         1.        ]


In [15]:
#find mode
remainder=np.mod(x,y) #using mod function
print(remainder)
remainder1=x%y  #using % operator
print(remainder1)

[1 2 3 0 0 6 7 0 0]
[1 2 3 0 0 6 7 0 0]


mathematical function

In [ ]:
#trigonometric function

sin_value=np.sin(x)
print(sin_value)

cos_value=np.cos(x)
print(cos_value)

deg_con=np.deg2rad(x)
print(deg_con)

deg_con1=np.rad2deg(deg_con)
print(deg_con1)



[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026]
[0.01745329 0.03490659 0.05235988 0.06981317 0.08726646 0.10471976
 0.12217305 0.13962634 0.15707963]


In [21]:
#log
x=np.array([1,10,100,1000])
log_value=np.log10(x)
print(log_value)

log_value1=np.log2(x)
print(log_value1)

sqrt=np.sqrt(x)
print(sqrt)

[0. 1. 2. 3.]
[0.         3.32192809 6.64385619 9.96578428]
[ 1.          3.16227766 10.         31.6227766 ]


In [22]:
x=np.array([1,10,100,1000])
s=np.sum(x)
print(s)

1111


In [23]:
#prefix sum
cumsum=np.cumsum(x)
print(cumsum)

[   1   11  111 1111]


Logical Function

In [ ]:
#comparison
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
greater_than=a>b
#greater_than=np.greater(a,b)  #using greater function
print(greater_than)

large_than=a<b
#large_than=np.less(a,b)  #using less function
print(large_than)

equal=a==b
#equal=np.equal(a,b)  #using equal function
print(equal)

[False False False  True  True]
[ True  True False False False]
[False False  True False False]


Sorting

In [27]:
#inplace
x=np.array([1,2,3,4,5])
x+=5
print(x)

[ 6  7  8  9 10]


In [29]:
x=np.array([90,60,1,20,30,32])
z=x.copy()
print(z)

z.sort()
print(z)

[90 60  1 20 30 32]
[ 1 20 30 32 60 90]


In [31]:
#copy sorting
print(x)

sorted_x=np.sort(x)
print(sorted_x)


[90 60  1 20 30 32]
[ 1 20 30 32 60 90]


2d array sorting

In [34]:
mat=np.array([
    [10,5,8],
    [40,10,2]
])
#horizon axis=1

hor_sorted=np.sort(mat,axis=1)
print("Horizontal sorting:")
print(hor_sorted)


vert_sorted=np.sort(mat,axis=0)
print("Vertical sorting:")
print(vert_sorted)

Horizontal sorting:
[[ 5  8 10]
 [ 2 10 40]]
Vertical sorting:
[[10  5  2]
 [40 10  8]]


Searching


In [35]:
print(mat)

[[10  5  8]
 [40 10  2]]


In [36]:
index=np.where(mat==10)
print(index)

(array([0, 1], dtype=int64), array([0, 1], dtype=int64))


In [ ]:
index=np.where(mat>10)
print(index)

array=np.where(mat>10,mat,1)  #if false it return 1 to replace the value
print(array)

(array([1], dtype=int64), array([0], dtype=int64))
[[ 1  1  1]
 [40  1  1]]


In [ ]:
x=np.array([10,100,8,16,100])

maximum_index=np.argmax(x)
print(maximum_index)

minimum_index=np.argmin(x)
print(minimum_index)

4
2


statistical function

In [ ]:
data=np.genfromtxt("student_scores.csv",delimiter=",",skip_header=1)
print(data)

[[56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [56]:
#statistics
math_marks=data[::,:1]
print(math_marks.T)

max_math_marks=np.max(math_marks)
print("Maximum math marks:",max_math_marks)

min_math_marks=np.min(math_marks)
print("Minimum math marks:",min_math_marks)


average_math_marks=np.mean(math_marks)
print("Average math marks:",average_math_marks)

median_math_marks=np.median(math_marks)
print("Median math marks:",median_math_marks)

#standard deviation
std_math_marks=np.std(math_marks)
print("Standard deviation of math marks:",std_math_marks)


[[56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84. 62.
  95.]]
Maximum math marks: 95.0
Minimum math marks: 45.0
Average math marks: 72.89473684210526
Median math marks: 73.0
Standard deviation of math marks: 14.100745545209584


correlation_coefficient

In [60]:
import numpy as np
study_hour=np.array([2,4,5,7,8])
exam_scores=np.array([65,75,78,88,92])

data=np.array([study_hour,exam_scores])

correlation=np.corrcoef(data)
print("Correlation coefficient between study hours and exam scores:")
print(correlation)

Correlation coefficient between study hours and exam scores:
[[1.         0.99859154]
 [0.99859154 1.        ]]


linear algebra

In [62]:
A=np.array([
    [1,2,3],
    [4,5,6]
])
B=np.array([
    [7,8,9],
    [9,8,7],
    [6,5,4]
    
])
dot_product=np.dot(A,B)
print("Dot product of A and B:")
print(dot_product)


#trace

print(np.trace(A))

Dot product of A and B:
[[ 43  39  35]
 [109 102  95]]
6


In [65]:
sq_matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

det_of_sq_matrix=np.linalg.det(sq_matrix)
print("Determinant of the square matrix:")
print(det_of_sq_matrix)

#rank of matrix
rank_of_sq_matrix=np.linalg.matrix_rank(sq_matrix)
print("Rank of the square matrix:")
print(rank_of_sq_matrix)

Determinant of the square matrix:
0.0
Rank of the square matrix:
2
